general_client_data:
    resource: "@GeneralClientDataBundle/Resources/config/routing.yml"
    prefix:   /

client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /

mongo_db:
    resource: "@MongoDBBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"