# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    custom_user_manager_id:
      class: UserBundle\Doctrine\UserManager
      arguments: [@security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, @fos_user.object_manager,%fos_user.model.user.class%, @doctrine.orm.entity_manager]
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
    my_user_provider:
        class:        MongoDBBundle\Security\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { twitter: twitter_id }]
  