CREATE SEQUENCE direccion_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE TABLE direccion (
    id INT NOT NULL,
    direccion VARCHAR(75) NOT NULL,
    PRIMARY KEY(id)
);

ALTER TABLE direccion ADD cliente_id INT DEFAULT NULL;

ALTER TABLE direccion
    ADD CONSTRAINT FK_CLIENTE_DIRECCION
    FOREIGN KEY (cliente_id)
    REFERENCES client (id);

CREATE INDEX IDX_CLIENTE_DIRECCION ON direccion (cliente_id);

