CREATE SEQUENCE telefono_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE TABLE telefono (
    id INT NOT NULL,
    numeroTelefono VARCHAR(9) NOT NULL,
    PRIMARY KEY(id)
);

ALTER TABLE telefono ADD cliente_id INT DEFAULT NULL;
ALTER TABLE telefono ADD CONSTRAINT FK_C1E70A7FDE734E51 FOREIGN KEY (cliente_id) REFERENCES client (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
CREATE INDEX IDX_C1E70A7FDE734E51 ON telefono (cliente_id);
