UserBundle\Entity\Usuario:
    properties:
        email:
            - Regex:
                pattern: "/[a-z\'0-9]+([._-][a-z\'0-9]+)*@([udv]+[.]+[edu]+[.]+[gt]+)/"
                message: "El dominio del correo tiene que ser de la UDV"
                groups: [EmailDomainValidation]

DocumentBundle\Entity\Documento:
    properties:
        curso:
            - NotNull: ~
